# .github/workflows/docker-publish.yml
name: Build and Push Docker Image

# Run this workflow on every push to the 'main' branch
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Grant permission to write to GitHub Packages

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Tag the image with the repository name and 'latest'
          # This will look like: ghcr.io/your-username/ollama-stt-tts:latest
          tags: ghcr.io/${{ github.repository }}:latest
